# -*- coding: utf-8 -*-
"""Ludu concept.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MUqAxKspKoyXesbfxZNScbTQmF1J2lk8
"""

import random
ludu = [1,2,3,4,5,6]
random_number = random.choice(ludu)
if random_number == 6:
  print('Yah, You have won the game')
else:
  print(random_number, 'is not 6. Play again!')