# -*- coding: utf-8 -*-
"""Make Slugify Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Tma6lBHMtor3ajsUVWAUEvkyamnwhcq
"""

def slugify(text):
  slug = text.strip().lower().replace(' ','-')
  while '--' in slug:
    slug = slug.replace('--','-')
  return slug
title = input('Enter Title: ')
slug = slugify(title)
print(slug)